export default {
  vowels: [
    {
      text: "/ɑ:/",
      textColor: "#fff",
      backgroundColor: "#7f2954",
      answer: "1",
    },
    {
      text: "/aɪ/",
      textColor: "#000",
      backgroundColor: "#c7b104",
      answer: "2",
    },
    {
      text: "/aʊ/",
      textColor: "#000",
      backgroundColor: "#c7b104",
      answer: "3",
    },
    {
      text: "/ɔ:/",
      textColor: "#000",
      backgroundColor: "#3d681a",
      answer: "4",
    },
    {
      text: "/ɔɪ/",
      textColor: "#000",
      backgroundColor: "#3d681a",
      answer: "5",
    },
    {
      text: "/oʊ/",
      textColor: "#000",
      backgroundColor: "#3d681a",
      answer: "6",
    },
    {
      text: "/e/",
      textColor: "#fff",
      backgroundColor: "#763332",
      answer: "7",
    },
    {
      text: "/eɪ/",
      textColor: "#fff",
      backgroundColor: "#763332",
      answer: "8",
    },
    {
      text: "/æ/",
      textColor: "#fff",
      backgroundColor: "#763332",
      answer: "9",
    },
    {
      text: "/ɪ/",
      textColor: "#fff",
      backgroundColor: "#2f60de",
      answer: "10",
    },
    {
      text: "/i:/",
      textColor: "#fff",
      backgroundColor: "#2f60de",
      answer: "11",
    },
    {
      text: "/i/",
      textColor: "#fff",
      backgroundColor: "#2f60de",
      answer: "11 phụ",
    },
    {
      text: "/ʊ/",
      textColor: "#fff",
      backgroundColor: "#232e20",
      answer: "12",
    },
    {
      text: "/u:/",
      textColor: "#fff",
      backgroundColor: "#232e20",
      answer: "13",
    },
    {
      text: "/u/",
      textColor: "#fff",
      backgroundColor: "#232e20",
      answer: "13 phụ",
    },
    {
      text: "/ʌ/",
      textColor: "#fff",
      backgroundColor: "#463140",
      answer: "14",
    },
    {
      text: "/ɜ:/",
      textColor: "#fff",
      backgroundColor: "#463140",
      answer: "15",
    },
    {
      text: "/ə/",
      textColor: "#fff",
      backgroundColor: "#463140",
      answer: "15 phụ",
    },
  ],
  consonants: [
    {
      text: "/p/",
      textColor: "#000",
      backgroundColor: "#37651d",
      answer: "1",
    },
    {
      text: "/b/",
      textColor: "#000",
      backgroundColor: "#37651d",
      answer: "2",
    },
    {
      text: "/f/",
      textColor: "#000",
      backgroundColor: "#37651d",
      answer: "3",
    },
    {
      text: "/v/",
      textColor: "#000",
      backgroundColor: "#37651d",
      answer: "4",
    },
    {
      text: "/k/",
      textColor: "#000",
      backgroundColor: "#085660",
      answer: "5",
    },
    {
      text: "/g/",
      textColor: "#000",
      backgroundColor: "#085660",
      answer: "6",
    },
    {
      text: "/θ/",
      textColor: "#fff",
      backgroundColor: "#6b4d63",
      answer: "7",
    },
    {
      text: "/ð/",
      textColor: "#fff",
      backgroundColor: "#6b4d63",
      answer: "8",
    },
    {
      text: "/s/",
      textColor: "#000",
      backgroundColor: "#cfba0f",
      answer: "9",
    },
    {
      text: "/z/",
      textColor: "#000",
      backgroundColor: "#cfba0f",
      answer: "10",
    },
    {
      text: "/ʃ/",
      textColor: "#000",
      backgroundColor: "#cfba0f",
      answer: "11",
    },
    {
      text: "/ʒ/",
      textColor: "#000",
      backgroundColor: "#cfba0f",
      answer: 12,
    },
    {
      text: "/t/",
      textColor: "#fff",
      backgroundColor: "#ac4d41",
      answer: "13",
    },
    {
      text: "/d/",
      textColor: "#fff",
      backgroundColor: "#ac4d41",
      answer: "14",
    },
    {
      text: "/j/",
      textColor: "#fff",
      backgroundColor: "#ac4d41",
      answer: "15",
    },
    {
      text: "/tʃ/",
      textColor: "#fff",
      backgroundColor: "#ac4d41",
      answer: "16",
    },
    {
      text: "/dʒ/",
      textColor: "#fff",
      backgroundColor: "#ac4d41",
      answer: "17",
    },
    {
      text: "/m/",
      textColor: "#fff",
      backgroundColor: "#263288",
      answer: "18",
    },
    {
      text: "/n/",
      textColor: "#fff",
      backgroundColor: "#263288",
      answer: "19",
    },
    {
      text: "/η/",
      textColor: "#fff",
      backgroundColor: "#263288",
      answer: "20",
    },
    {
      text: "/w/",
      textColor: "#fff",
      backgroundColor: "#33402d",
      answer: "21",
    },
    {
      text: "/r/",
      textColor: "#fff",
      backgroundColor: "#33402d",
      answer: "22",
    },
    {
      text: "/l/",
      textColor: "#fff",
      backgroundColor: "#df7b32",
      answer: "23",
    },
    {
      text: "/h/",
      textColor: "#fff",
      backgroundColor: "#8c477e",
      answer: "24",
    },
  ],
};
export const DATA_TYPE = {
  VOWELS: "vowels",
  CONSONANTS: "consonants",
};
